sonar.projectKey=wraglet
sonar.sources=src
sonar.tests=src,e2e
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts
sonar.exclusions=**/.env,**/.env.*,**/.next/**,**/node_modules/**,**/coverage/**,**/storybook-static/**,**/playwright-report/**,**/test-results/**
